### PR TITLE
2fa - allow populating the login data structure via callback for 2fa

### PR DESCRIPTION
**Pull request by commonism**
This allows supplying 2fa tokens to the login.

e.g. using pyotp
```python
def mfa():
    totp = pyotp.TOTP(otpseed)
    return {"twoFactorToken": str(totp.now()), "twoFactorProvider": "0","twoFactorRemember": "0"}

client = Client(server, email, password, mfa_cb=mfa) 
client.sync()
```

### CODE REVIEW

**Comment by commonism** [comment]
As I see this allows API auth as well - maybe it's better to have this as general auth_cb which gets the login data passed for easy manipulation?

```python
def authenticate(data: Dict[str, str]):
…
     return data

client = Client(server, email, password, auth_cb=authenticate) 
```

**Comment by kiorky** [comment]
Thanks for the contribution !

I am not sure to understand well what you mean. If it's a spelling suggestion, yes i would argue that `auth_cb`  (both in argument and attribute) is a better alternative.

Would you mind then updating this PR as i'm more than willing to merge it !

**Comment by commonism** [comment]
Had some spare characters, made it authentication_cb.
No docs to add this to?

**Comment by kiorky** [comment]
I was going to do it myself after merge, but you can of course do it yourself by adding an exemple to https://github.com/corpusops/bitwardentools/blob/main/USAGE.md (like copy/pasting/adapting what you already posted in commit message)

And also add changelog entry in https://github.com/corpusops/bitwardentools/blob/main/CHANGES.md

So i'm waiting for it, or tell me to do it myself !

**Comment by commonism** [comment]
just go ahead - you know how it is meant to look like

**Pull request merged**
